### ISSUE TITLE
Email Support (Lite) 

### ISSUE THREAD

**Issue by jarrod-dalton** [NikKrieger/projects#2]
It would be neat to have a few self-populated emails relating to projects accessible via some function(s).

I have outlook as my default client, and `browseURL("mailto://email@address1.com, email@address2.org")` works quite handily.

This leads to some basic functions like `email_team(id)` or `email_authors(authors)` which are essentially `mailto://` link constructors.

For `email_team()`, would it be possible to recognize whether your are actually in a project's .Rproj environment and not require the user to look up the project ID?

**Comment by NikKrieger** [comment]
See the new function `email_authors()`. You can specify a project. Or, if you have a `projects()` project open, you can run it without arguments.
